name: prestamo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_mask: ^2.0.1
  easy_rich_text: ^2.0.0
  fl_chart: ^0.63.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
